### ISSUE TITLE
Error when make -j

### ISSUE THREAD

**Issue by yan-map** [ad-freiburg/loom#10]
```
src/transitmap/output/protobuf/CMakeFiles/proto.dir/build.make:73: *** target pattern contains no '%'. Stop.
make[1]: *** [CMakeFiles/Makefile2:668: src/transitmap/output/protobuf/CMakeFiles/proto.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  3%] Built target dot_dep
[ 13%] Built target shared_dep
[ 30%] Built target util
[ 32%] Built target loom_dep
make: *** [Makefile:146: all] Error 2
```

**Comment by patrickbr** [comment]
Which OS / version do you have? How exactly did you prepare the build environment (`cmake ..`?). What is your `cmake` and `make` version?

**Comment by yan-map** [comment]
> Which OS / version do you have? How exactly did you prepare the build environment (`cmake ..`?). What is your `cmake` and `make` version?

Ubuntu 20.04.6 LTS
Cmake 3.27.8
GNU Make 4.2.1
gcc 9.4.0

I've used `cmake ..`
and then tried `make -j `and `make install`

Unfortunately, the Docker method is not suitable when using GTFS: an error occurs:
`Cannot read from ZIP file, was compiled without libzip`

**Comment by patrickbr** [comment]
That is strange, because we build on Ubuntu 20.04 with Github actions, and everything works smoothly there (https://github.com/ad-freiburg/loom/actions/runs/6548744759/job/17784104184).

As the error seems to be related to libprotobuf, I just tried compiling without it, but that also worked without problems. 

After `cmake ..`, could you post the full contents of `build/src/transitmap/output/protobuf/CMakeFiles/proto.dir/build.make` here?

**Comment by patrickbr** [comment]
`libzip` and `libprotobuf-dev` are now installed in the Dockerfile. Note, however, that you cannot give the ZIP path directly to the Docker run command, as Docker has no access to this file inside the container. You have to mount some path inside the Container to achieve that.

**Comment by hydraseek-pauseai** [comment]
I'm also getting the exact same error originally mentioned in this thread. I've been trying a million different things to try and get it to work, and it's compiled successfully once, but I have no idea why. It seems to have something to do with the C compiler? Help would be appreciated. Thanks!

`src/transitmap/output/protobuf/CMakeFiles/proto.dir/build.make:73: *** target pattern contains no '%'. Stop.
make[1]: *** [CMakeFiles/Makefile2:668: src/transitmap/output/protobuf/CMakeFiles/proto.dir/all] Error 2`
