### ISSUE TITLE
Problem on mvt file generation

### ISSUE THREAD

**Issue by placko** [ad-freiburg/loom#12]
Hi,
I am trying to create an mvt file but the generated file is empty.
Maybe I'm not following the good procedure...
Here is the command I use: 
`docker run -i loom transitmap --render-engine=mvt --mvt-path=. -z=10,11 < loomed_file.json > render.mvt`
The svg file generates well (`docker run -i loom transitmap < loomed_file.json > render.svg`) but not the mvt file.
Can you help me ?

**Comment by patrickbr** [comment]
The MVT tiles are written to the folder given via `--mvt-path`. There is no output written to stdout, so your file `render.mvt` should indeed be empty. The reason is that MVT tiles consist of many files, not a single file like in the SVG setting.

Can you try creating a folder `mvt`, setting `--mvt-path mvt` and then checking the `mvt` folder?

**Comment by placko** [comment]
Thank you for your reply.
I created an mvt folder then run the command :
`docker run -i loom transitmap --render-engine=mvt --mvt-path=mvt -z=10,11 < loomed_file.json`
but the folder mvt remains empty.

**Comment by patrickbr** [comment]
Is the folder `mvt` mounted inside the docker container?

**Comment by placko** [comment]
The folder `mvt` is mounted inside the docker container but it is empty

**Comment by patrickbr** [comment]
Interesting, could you maybe upload the `loomed_filed.json` somewhere so that I can test this myself?

**Comment by patrickbr** [comment]
It works on my machine. However, if the tiles cannot be written, `transitmap` failed silently until now. I changed this in the current master, it now throws an error if either the output directory couldn't be created, of a tile couldn't be written.

Can you try again with the latest master? And can you give your exact Docker command (including the mount parameters for the `mvt` folder?)

**Comment by placko** [comment]
Thanks for the last master. but i got an error.
Here you can find the docker command :
```
FROM ubuntu:20.04
ARG GRB_VERSION=9.1.2
ARG GRB_SHORT_VERSION=9.1

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install --no-install-recommends -y\
       ca-certificates  \
	   libglpk-dev \
	   glpk-utils \
	   coinor-libcbc-dev \
	   coinor-cbc \
	   libprotobuf-dev \
	   libzip-dev \
	   protobuf-compiler \
       make \
       cmake \
       wget \
	   g++ \
       git \
    && update-ca-certificates \
    && wget -q https://packages.gurobi.com/${GRB_SHORT_VERSION}/gurobi${GRB_VERSION}_linux64.tar.gz \
    && tar -xf gurobi${GRB_VERSION}_linux64.tar.gz  \
    && rm -f gurobi${GRB_VERSION}_linux64.tar.gz \
    && mv -f gurobi* gurobi \
    && rm -rf gurobi/linux64/docs

ENV GUROBI_HOME /opt/gurobi/linux64
ENV PATH $PATH:$GUROBI_HOME/bin:/loom/build
ENV LD_LIBRARY_PATH $GUROBI_HOME/lib

RUN git clone --recurse-submodules https://github.com/ad-freiburg/loom /loom

ENV GRB_LICENSE_FILE /gurobi/gurobi.lic

RUN cd /loom && rm -rf build && mkdir build && cd build && cmake .. && make -j20 install

WORKDIR /

COPY ./mvt /loom/mvt
COPY ./loomed-file.json /loom/loomed-file.json

CMD loom
```
then run  `docker build -t loom .`
and when i run `cat loomed-file.json | sudo docker run -i loom transitmap --render-engine mvt --mvt-path mvt`
i've got this error :
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not create output directory mvt/14
```

**Comment by patrickbr** [comment]
This means that the folder `mvt` inside the Docker container was not writable. You are copying your local `mvt` folder to `/loom/mvt`, not `/mvt`. Moreover, you won't have access to any tiles written there, they will reside purely inside the container.

This should work:

`cat loomed-file.json | docker run -i -v ./mvt:/mvt loom transitmap --render-engine mvt --mvt-path mvt`

With `-v ./mvt:/mvt`, you are mounting your local folder `mvt` to the folder `/mvt` inside the docker container.

**Comment by placko** [comment]
Hi,
thank you for your reply, it works well !

**Comment by placko** [comment]
Hi,
thank you for your reply, it works well !
