### ISSUE TITLE
make -j fails on Apple silicon with "C++ versions less than C++14 are not supported."

### ISSUE THREAD

**Issue by tylershuster** [ad-freiburg/loom#15]
See title. Setup is a fairly normal M1 Max MacBook Pro. I've tried making sure gcc is being used from homebrew @14 instead of Apple's clang. That didn't make a difference.

On `cmake ..` I get "Protobuf compiler version 3.21.12 doesn't match library version 5.27.0" and indeed running `protoc --version` returns 3.21.12. I'm happy to provide any more information.

**Comment by patrickbr** [comment]
Strange, we are doing continuous builds on MacOS 11 and 12, and these work without problems. Can you post the output of `clang --version` and `gcc --version`? The second error message hints that you somehow have a `protoc` that does not match your `libprotobuf` version. Did you maybe install them from separate sources?

**Comment by patrickbr** [comment]
Maybe it would also be useful for you to look into our: [`build.yml`](https://github.com/ad-freiburg/loom/blob/master/.github/workflows/build.yml)

There you can see exactly which things are install on MacOS.

**Comment by tylershuster** [comment]
No worries, I'm attaching the output of my C dependencies. I don't think I installed protoc from elsewhere, but I have done some GTFS work in the past so it's possible. I will take a closer look at the build.yml as well.

`clang --version`:
```
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

`gcc --version`:
```
gcc (Homebrew GCC 14.1.0_1) 14.1.0
Copyright (C) 2024 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by patrickbr** [comment]
BTW, if you do not need vector tile support of LOOM, feel free to compile it without `libprotobuf`. For example, you can simple comment out line 26 (`find_package(Protobuf)`) in `CMakeLists.txt`.
