### ISSUE TITLE
Compiled Without Libzip

### ISSUE THREAD

**Issue by hydraseek-pauseai** [ad-freiburg/loom#18]
Just checking to see if you have any idea what this libzip error is about, since it seems like this error is only part of this program. I've tried installing libzip-dev and recompiling the build, but I'm still getting the same error. 
```
tfXXXX@XXXX:~/loom/build$ ./gtfs2graph njtgtfs.zip > output.json
[2024-09-13 16:32:58.823] ERROR: Could not parse input GTFS feed, reason was:
njtgtfs.zip: **Cannot read from ZIP file, was compiled without libzip**
```
Thanks!

**Comment by mattnovelli** [comment]
Also getting this. Did you find a fix?

**Comment by patrickbr** [comment]
This error simply means that `loom` was compiled without `libzip`. `libzip` is optional, but without it, `loom` cannot read ZIP-files. On debianesque systems, you need to have `libzip-dev` installed before compilation. On Mac, the package is named `libzip` afaik.
