### ISSUE TITLE
Questions while installing on Mac

### ISSUE THREAD

**Issue by mclaeysb** [ad-freiburg/loom#4]
Hi

Thanks for building this! Being very excited to test this out, I tried installing on my mac today (macOS 13.6).

Here are some questions I have

- I see there is a need to install `gurobi`. I understand this is not free software. Is it possible to install this for free somehow?
- Once installed, do I have to add the `gtfs2graph`etc commands to my `$PATH`? If so, what paths should I use?

Ps: On the Readme in the Building and Installation heading I think a `cd loom` is missing after the `git-clone`

Thanks in advance
Manuel

**Comment by patrickbr** [comment]
Hi there,

you don't need gurobi, all tools should automatically fall back to a free solver (try COIN-OR CBC or glpk) if available, or fall back to a heuristic if not solver is available.

At least on debianesque systems, `make install` should make commands like `gtfs2graph` globally available. We never tested this on a Mac and there is another issue with additional problems on Mac still open (https://github.com/ad-freiburg/loom/issues/1). I was quite busy the last months and never got around to setting up a Mac build environment, but will do so next week.

The README is now updated and includes the `cd loom` :)

**Comment by mclaeysb** [comment]
Thanks for you reply - and your ongoing work. I will test this shortly!
